name:                fin
version:             0.1.0.0

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

ghc-options:
  - -Wall

library:
  source-dirs: src
  dependencies:
  - containers
  - pretty-terminal
  default-extensions:
  - NamedFieldPuns  # https://downloads.haskell.org/ghc/latest/docs/html/users_guide/exts/record_puns.html#extension-NamedFieldPuns

executables:
  fin-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fin
    - containers
    - pretty-terminal

tests:
  fin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fin
    - containers
